LEVELS = [
   ['     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '                                                             ',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '                                                             ',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '                                                             ',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '                                                             ',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '                                                             ',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '                                                             ',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '                                                             ',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '                                                             ',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '                                                             ',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '                                                             ',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '                                                             ',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '                                                             ',
    '                                                  X          ',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    '     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    '     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    '     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
]
];