LEVELS = [
     {"record":"00:03.450","cells":["                      z                       ",
                                    " gggggggggggggggggggggzgggggggggggggggggggggg ",
                                    " g                    z                     g ",
                                    " g hhhhhhhhhhhhhhhhhhhzhhhhhhhhhhhhhhhhhhhh g ",
                                    " g h                  z                   h g ",
                                    " g h jjjjjjjjjjjjjjjjjzjjjjjjjjjjjjjjjjjj h g ",
                                    " g h j                z                 j h g ",
                                    " g h j kkkkkkkkkkkkkkkzkkkkkkkkkkkkkkkk j h g ",
                                    " g h j k              z               k j h g ",
                                    " g h j k lllllllllllllzllllllllllllll k j h g ",
                                    " g h j k l            z             l k j h g ",
                                    " g h j k l            z             l k j h g ",
                                    " g h j k l pppppppppppzppppppppppp  l k j h g ",
                                    " g h j k l pppppppppppzppppppppppp  l k j h g ",
                                    " g h j k l pp         z         pp  l k j h g ",
                                    " g h j k l pp         z         pp  l k j h g ",
                                    " g h j k l pp  qqqqqqq qqqqqqq  pp  l k j h g ",
                                    " g h j k l pp  qqqqqqq qqqqqqq  pp  l k j h g ",
                                    "zzzzzzzzzzzzzzzzzzzzzzXzzzzzzzzzzzzzzzzzzzzzzz",
                                    " g h j k l pp  qqqqqqq qqqqqqq  pp  l k j h g ",
                                    " g h j k l pp  qqqqqqq qqqqqqq  pp  l k j h g ",
                                    " g h j k l pp         z         pp  l k j h g ",
                                    " g h j k l pp         z         pp  l k j h g ",
                                    " g h j k l pppppppppppzppppppppppp  l k j h g ",
                                    " g h j k l pppppppppppzppppppppppp  l k j h g ",
                                    " g h j k l            z             l k j h g ",
                                    " g h j k l            z             l k j h g ",
                                    " g h j k lllllllllllllzllllllllllllll k j h g ",
                                    " g h j k              z               k j h g ",
                                    " g h j kkkkkkkkkkkkkkkzkkkkkkkkkkkkkkkk j h g ",
                                    " g h j                z                 j h g ",
                                    " g h jjjjjjjjjjjjjjjjjzjjjjjjjjjjjjjjjjjj h g ",
                                    " g h                  z                   h g ",
                                    " g hhhhhhhhhhhhhhhhhhhzhhhhhhhhhhhhhhhhhhhh g ",
                                    " g                    z                     g ",
                                    " gggggggggggggggggggggzgggggggggggggggggggggg ",
                                    "                      z                       "]}
    ,{"record":"00:01.001","cells":[" X"]}
    ,{"record":"00:18.129","cells":["                                                                      ",
                                    "                                                                      ",
                                    "                                                                      ",
                                    "                                                                      ",
                                    "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH HHH HHHHH H",
                                    "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh hhh hhhhh h",
                                    "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh hhh hhhhh h",
                                    "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh hhh hhhhh h",
                                    "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh hhh hhhhh h",
                                    "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh hhh hhhhh h",
                                    "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh hhh hhhhh h",
                                    "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh hhh hhhhh h",
                                    "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh hhh hhhhh h",
                                    "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh hhh hhhhh h",
                                    "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh hhh hhhhh h",
                                    "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh hhh hhhhh h",
                                    "                                                                      ",
                                    "                                                                      ",
                                    "                                                                      ",
                                    "NNNNNNNNNNNNNNNNNNNNNNNNNN NNNNNNNNNNNNNNNNNNNNNNN N NN         NNNNNN",
                                    "nnnnnnnnnnnnnnnnnnnnnnnnnn nnnnnnnnnnnnnnnnnnnnnnn n nn         nnnnnn",
                                    "nnnnnnnnnnnnnnnnnnnnnnnnnn nnnnnnnnnnnnnnnnnnnnnnn n nn         nnnnnn",
                                    "nnnnnnnnnnnnnnnnnnnnnnnnnn nnnnnnnnnnnnnnnnnnnnnnn n nn         nnnnnn",
                                    "                                                                      ",
                                    "                                                                      ",
                                    "A AAA AAAAAAAA                                                        ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "a aaa aaaaaaaa                         BBBB                           ",
                                    "a aaa aaaaaaaa                         bbb                            ",
                                    "a aaa aaaaaaaa                         b  b                           ",
                                    "a aaa aaaaaaaa                         b                              ",
                                    "a aaa aaaaaaaa                         b                              ",
                                    "a aaa aaaaaaaa                         b                              ",
                                    "a aaa aaaaaaaa                         b                              ",
                                    "a aaa aaaaaaaa                         b                              ",
                                    "a aaa aaaaaaaa                         b                              ",
                                    "a aaa                                  b                              ",
                                    "                                       b                              ",
                                    "a aaa aaaaaaaa                         b                              ",
                                    "a aaa                                  b                              ",
                                    "a aaa aaaaaaaa                         b                              ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "                                                                      ",
                                    "                                                                      ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "                                                                      ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "                                                                      ",
                                    "                                                                      ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "                                                                      ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "                                                                      ",
                                    "                                                                      ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "                                          X                           ",
                                    "                                                                      ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "                                                                      ",
                                    "                                                                      ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "                                                                      ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "                                                                      ",
                                    "                                                                      ",
                                    "a aaa                                                                 ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "      aaaaaaaa                                                        ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "                                                                      ",
                                    "a aaa aaaaaaaa                                                        ",
                                    "                                                                      ",
                                    "                                                                      ",
                                    "                                                                      ",
                                    "                                                                      ",
                                    "                                                                      ",
                                    "                                                                      ",
                                    "                                                                      ",
                                    "                                                                      ",
                                    "                                                                      ",
                                    "                                                                      ",
                                    "                                                                      "]}
    ,{"record":"00:01.001","cells":[" X   xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "                                                             ",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "                                                             ",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "                                                             ",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "                                                             ",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "                                                             ",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "                                                             ",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "                                                             ",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "                                                             ",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "                                                             ",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "                                                             ",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "                                                             ",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "                                                             ",
                                    "                                                             ",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "     xxxx       xxxx    x x x x x x x x x x x x      xxxxxxxx",
                                    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                                    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                                    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                                    "     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                                    "     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]}
    ,{"record":"00:01.001","cells":["      ",
                                    "X     ",
                                    "      ",
                                    "      ",
                                    "      "]}
];
